### ISSUE TITLE
invalid 'actionAsync' context when promises resolve at the same time in different actionAsync

### ISSUE THREAD

**Issue by Korkemoms** [mobxjs/mobx-utils#239]
Im getting the following error when i run the code below

`mobx-utils.module.js:6 Uncaught (in promise) Error: [mobx-utils] invalid 'actionAsync' context when finishing action 'actionAsync1'. an action context for 'actionAsync2' was found instead. did you await inside an 'actionAsync' without using 'task(promise)'? did you forget to await the task?`

```
const r = new Promise(resolve => {
  setTimeout(() => {
    resolve(null);
  }, 1000);
});

const actionAsync1 = actionAsync("actionAsync1", async () => {
  await task(r);
});

const actionAsync2 = actionAsync("actionAsync2", async () => {
  await task(r);
});
actionAsync1();
actionAsync2();
```

It happens with both the following version combinations:

```
    "mobx": "4.15.4",
    "mobx-utils": "5.5.3",
```

```
    "mobx": "5.15.4",
    "mobx-utils": "5.5.3",
```

**Comment by xaviergonz** [comment]
Thanks, just made a PR that should solve this

**Comment by Korkemoms** [comment]
Will there be a release soon with this fix in? Need this to be fixed in our application.

Thanks for the great work

**Comment by xaviergonz** [comment]
Should be out in 5.5.4

**Comment by jpgarcia** [comment]
Hi @xaviergonz it seems that the issue is still happening in previous versions of Node. 

Checkout the following video capture:

Node 13.12.0 ✅ / Node 9.11.2 ❌ / Node  8.17.0 ❌

![mobx-utils](https://user-images.githubusercontent.com/95109/78455862-f9f4a600-7676-11ea-9812-0dc60c74761a.gif)

Maybe we should reopen this issue?

**Comment by xaviergonz** [comment]
Thanks, it wasn't caught before because it was tested against the transpiled async/await of typescript (which does work on those node versions). Do you know if react-native includes a setImmediate function?

**Comment by xaviergonz** [comment]
Also, which node version (if any) does react-native use?

**Comment by xaviergonz** [comment]
Could you build the PR https://github.com/mobxjs/mobx-utils/pull/244 and link it into your project and see if it fixes it? I tested it with node 8.17.0 with async transpilation off and it seems ok now, but I don't know what will happen with react-native

**Comment by jpgarcia** [comment]
Hey @xaviergonz I built a new version based on #244 and it worked on the node versions I tested before but I can confirm now that the fix is actually not working for **React Native** as I reported on #243 so now we have:

Node 13.12.0 ✅ / Node 9.11.2 ✅ / Node 8.17.0 ✅ /  React Native ❌

Regarding the javascript engine you can find more info here https://reactnative.dev/docs/javascript-environment

Also there is a special **Timers** section in React Native docs where you can find more info related to **setImmediate** https://reactnative.dev/docs/timers

Thank you very much for your effort on fixing this one!

**Comment by xaviergonz** [comment]
Thanks, care to give the new version a try? Also, could you please check if react-native offers either queueMicrotask and/or process.nextTick?

**Comment by jpgarcia** [comment]
Wow dude! it worked like a charm!

I did a little research and it seems that React Native does not support those 😢 It seems that they're all hacking the issue by doing things like:

```js
process.nextTick = setImmediate
```

it would be awesome to have a new release with your fix! 🚀

**Comment by xaviergonz** [comment]
v5.5.6

**Comment by jpgarcia** [comment]
Hi @xaviergonz I think I found a new issue related to errors 😢 

Node 13.12.0 ✅ / Node 9.11.2 ❌ / Node 8.17.0 ❌ / RN ❌

This is the snippet:

```js
const {actionAsync, task} = require('mobx-utils');

const r = (shouldThrow) =>
  new Promise((resolve, reject) => {
    setTimeout(() => {
      if (shouldThrow) {
        reject('Error');
        return;
      }
      resolve(Date.now());
    }, 1000);
  });

const actionAsync1 = actionAsync('actionAsync1', async () => {
  try {
    const result = await task(r(true));
    console.log(`actionAsync1 ${result}`);
  } catch (err) {
    console.log('actionAsync1 error');
  }
});

const actionAsync2 = actionAsync('actionAsync2', async () => {
  try {
    const result = await task(r(false));
    console.log(`actionAsync2 ${result}`);
  } catch (err) {
    console.log('actionAsync2 error');
  }
});

actionAsync1();
actionAsync2();
// Notice I'm calling this again
actionAsync1();
```

The output:

```bash
actionAsync1 error
actionAsync1 error
actionAsync2 1586267005653
(node:66211) UnhandledPromiseRejectionWarning: Error: [mobx-utils] invalid 'actionAsync' context when finishing action 'actionAsync1'. an action context for 'actionAsync1' was found instead. did you await inside an 'actionAsync' without using 'task(promise)'? did you forget to await the task?
    at fail$1 (/Users/juanpablogarcia/Projects/jpgarcia/actionasync/node_modules/mobx-utils/mobx-utils.umd.js:10:11)
    at finish (/Users/juanpablogarcia/Projects/jpgarcia/actionasync/node_modules/mobx-utils/mobx-utils.umd.js:1774:33)
    at /Users/juanpablogarcia/Projects/jpgarcia/actionasync/node_modules/mobx-utils/mobx-utils.umd.js:1806:25
    at step (/Users/juanpablogarcia/Projects/jpgarcia/actionasync/node_modules/mobx-utils/mobx-utils.umd.js:1570:23)
    at Object.next (/Users/juanpablogarcia/Projects/jpgarcia/actionasync/node_modules/mobx-utils/mobx-utils.umd.js:1551:53)
    at fulfilled (/Users/juanpablogarcia/Projects/jpgarcia/actionasync/node_modules/mobx-utils/mobx-utils.umd.js:1542:58)
    at <anonymous>
(node:66211) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:66211) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by xaviergonz** [comment]
Care to check PR https://github.com/mobxjs/mobx-utils/pull/246 ? Thanks!

**Comment by jpgarcia** [comment]
Yes it is working!

**Comment by xaviergonz** [comment]
v5.5.7
